export const SET_MESSAGE = "SET_MESSAGE";

export const GET_COMMUNITY_TYPES = "GET_COMMUNITY_TYPES";
export const GET_COMMUNITY_TYPES_SUCCESS = "GET_COMMUNITY_TYPES_SUCCESS";
export const GET_COMMUNITY_TYPES_FAILURE = "GET_COMMUNITY_TYPES_FAILURE";

export const GET_OCCUPANCY_TYPES = "GET_OCCUPANCY_TYPES";
export const GET_OCCUPANCY_TYPES_SUCCESS = "GET_OCCUPANCY_TYPES_SUCCESS";
export const GET_OCCUPANCY_TYPES_FAILURE = "GET_OCCUPANCY_TYPES_FAILURE";

export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";

export const ADD_COMMUNITY = "ADD_COMMUNITY";
export const ADD_COMMUNITY_SUCCESS = "ADD_COMMUNITY_SUCCESS";
export const ADD_COMMUNITY_FAILURE = "ADD_COMMUNITY_FAILURE";

export const GET_COMMUNITY = "GET_COMMUNITY";
export const GET_COMMUNITY_SUCCESS = "GET_COMMUNITY_SUCCESS";
export const GET_COMMUNITY_FAILURE = "GET_COMMUNITY_FAILURE";

export const ADD_GATE = "ADD_GATE";
export const ADD_GATE_SUCCESS = "ADD_GATE_SUCCESS";
export const ADD_GATE_FAILURE = "ADD_GATE_FAILURE";

export const EDIT_GATE = "EDIT_GATE";
export const EDIT_GATE_SUCCESS = "EDIT_GATE_SUCCESS";
export const EDIT_GATE_FAILURE = "EDIT_GATE_FAILURE";

export const DENEST_GATE = "DENEST_GATE";
export const DENEST_GATE_SUCCESS = "DENEST_GATE_SUCCESS";
export const DENEST_GATE_FAILURE = "DENEST_GATE_FAILURE";

export const GET_GATE = "GET_GATE";
export const GET_GATE_SUCCESS = "GET_GATE_SUCCESS";
export const GET_GATE_FAILURE = "GET_GATE_FAILURE";

export const TOGGLE_GATE = "TOGGLE_GATE";
export const TOGGLE_GATE_SUCCESS = "TOGGLE_GATE_SUCCESS";
export const TOGGLE_GATE_FAILURE = "TOGGLE_GATE_FAILURE";
