export const SET_MESSAGE = "SET_MESSAGE";

export const GET_COMMUNITY_TYPES = "GET_COMMUNITY_TYPES";
export const GET_COMMUNITY_TYPES_SUCCESS = "GET_COMMUNITY_TYPES_SUCCESS";
export const GET_COMMUNITY_TYPES_FAILURE = "GET_COMMUNITY_TYPES_FAILURE";

export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";

export const ADD_COMMUNITY = "ADD_COMMUNITY";
export const ADD_COMMUNITY_SUCCESS = "ADD_COMMUNITY_SUCCESS";
export const ADD_COMMUNITY_FAILURE = "ADD_COMMUNITY_FAILURE";
